const { Router } = require('express')
const router = Router()
// Hosts
const episode = require('./client/routers/episode.router')
const auth = require('./client/routers/auth.router')
const vote = require('./client/routers/vote.router')
const follow = require('./client/routers/follow.router')
const comment = require('./client/routers/comment.router')
const anime = require('./client/routers/anime.router')
const user = require('./client/routers/user.router')
const language = require('./client/routers/language.router')
const secure = require('./client/routers/secure.router')
const search = require('./client/routers/search.router')
// Router Use
router.use(episode)
router.use(auth)
router.use(vote)
router.use(follow)
router.use(comment)
router.use(anime)
router.use(user)
router.use(language)
router.use(secure)
router.use(search)

module.exports = router